const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
let src=fs.readFileSync('src/tokenizer.js','utf8').replace(/export function /g,'function ').replace(/export const /g,'const ');src+='\nmodule.exports={tokenizeBbcode,resolveHighlightRanges};';const sandbox={module:{exports:{}}};vm.runInNewContext(src,sandbox);const {tokenizeBbcode,resolveHighlightRanges}=sandbox.module.exports;
test('tags style urls colors numbers entities unicode CRLF',()=>{const text='中文\r\n[style color #ffaa00 width 10px][url=https://x.test/a]&#123;[/url][/style]';const types=new Set(tokenizeBbcode(text).map(x=>x.type));for(const type of ['tag','attribute','color','number','url','entity'])assert.ok(types.has(type),type)});
test('code body blocks general highlighting',()=>{const text='[code]https://hidden #ffffff 12px[/code] https://shown';const ranges=tokenizeBbcode(text);const innerStart=text.indexOf('https://hidden');assert.equal(ranges.some(r=>r.start===innerStart&&r.type==='url'),false);assert.equal(ranges.some(r=>r.type==='url'&&text.slice(r.start,r.end).includes('shown')),true)});
test('resolved ranges never overlap',()=>{const text='[url=https://x.test]';const rs=resolveHighlightRanges(text.length,tokenizeBbcode(text));for(let i=1;i<rs.length;i++)assert.ok(rs[i-1].end<=rs[i].start)});

test('comment extensions are classified and code remains blocked',()=>{const text='[comment // ++目录][comment // 名称!文本][comment // 属性名!属性][comment // #海报!图片 = https://x.test/a.png][code][comment // ++隐藏][/code]';const ranges=tokenizeBbcode(text);const parts=t=>ranges.filter(r=>r.type===t).map(r=>text.slice(r.start,r.end));assert.ok(parts('commentMarker').includes('++'));assert.ok(parts('commentName').includes('目录'));assert.ok(parts('commentFeature').includes('!文本'));assert.ok(parts('commentFeature').includes('!属性'));assert.ok(parts('commentName').includes('海报'));assert.ok(parts('url').includes('https://x.test/a.png'));assert.equal(parts('commentName').includes('隐藏'),false)});
test('suffix comment markers are classified',()=>{const text='[comment // 同名目录++][comment // 同名目录--]';const ranges=tokenizeBbcode(text);assert.deepEqual(Array.from(ranges.filter(r=>r.type==='commentMarker').map(r=>text.slice(r.start,r.end)).filter(x=>x!=='//')),['++','--'])});
function oldResolve(length,ranges){const priority={bracket:1,close:2,tag:2,attribute:3,value:1,url:5,color:5,number:4,entity:5,commentMarker:6,commentName:5,commentFeature:6};const accepted=[];for(const r of [...ranges].sort((a,b)=>(priority[b.type]||0)-(priority[a.type]||0)||a.start-b.start)){let fs=[{...r,start:Math.max(0,r.start),end:Math.min(length,r.end)}];for(const o of accepted)fs=fs.flatMap(f=>f.end<=o.start||f.start>=o.end?[f]:[...(f.start<o.start?[{...f,end:o.start}]:[]),...(f.end>o.end?[{...f,start:o.end}]:[])]);accepted.push(...fs)}return accepted.filter(r=>r.start<r.end).sort((a,b)=>a.start-b.start)}
test('sweep resolver preserves old randomized semantics',()=>{let seed=123456;const rand=()=>((seed=Math.imul(seed,1664525)+1013904223>>>0)/2**32);const types=['value','tag','number','url','commentMarker'];for(let round=0;round<300;round++){const ranges=Array.from({length:Math.floor(rand()*20)},()=>{const start=Math.floor(rand()*40),end=start+1+Math.floor(rand()*15);return{start,end,type:types[Math.floor(rand()*types.length)]}});assert.deepEqual(JSON.parse(JSON.stringify(resolveHighlightRanges(50,ranges))),JSON.parse(JSON.stringify(oldResolve(50,ranges))))}});
test('dense 300 line highlighting stays practical',()=>{const text=Array(300).fill('[style color #ffffff width 10px][url=https://x.test]x[/url][/style]').join('\n');const start=performance.now(),tokens=tokenizeBbcode(text),resolved=resolveHighlightRanges(text.length,tokens),elapsed=performance.now()-start;assert.ok(tokens.length>1000&&resolved.length>1000);assert.ok(elapsed<100,`elapsed ${elapsed}ms`)});
