const IMAGE_TAG_RE = /((?:\[\$deleted\]\s*)?(?:\[\$name\s*=\s*[^\]]*?\]\s*)*)\[img\]([\s\S]*?)\[\/img\]/gi;
const NAME_TAG_RE = /\[\$name\s*=\s*([^\]]*?)\]/gi;
const NGA_HOST_RE = /^(?:img\d?\.ngacn\.cc|img\d?\.nga\.cn|ngaimg\.178\.com|img\d?\.nga\.178\.com|img\.nga\.donews\.com|img\.nga\.bnbsky\.com|user-file\.nga\.178\.com)$/i;
const VARIANT_RE = /(?:\.,?(org|medium|thumb|thumb_s|thumb_ss)|\.(org|medium|thumb|thumb_s|thumb_ss))\.(jpe?g)$/i;
const IMAGE_EXT_RE = /\.(?:gif|jpe?g|png|bmp|webp)$/i;
function normalizeText(value){return String(value==null?'':value).trim().replace(/&amp;/gi,'&');}
function parseImageReference(value){const rawUrl=normalizeText(value);if(!rawUrl)return{rawUrl,identity:'',fullSizeUrl:'',path:'',variant:'',isNga:false,isImage:false,isDeletionRemnant:false};const withoutVariant=rawUrl.replace(VARIANT_RE,'');const variantMatch=rawUrl.match(VARIANT_RE);let path='';const local=withoutVariant.match(/^(?:\.\/|\/)?(mon_\d+\/.+)$/i)||withoutVariant.match(/^\/?attachments\/(mon_\d+\/.+)$/i);if(local)path=local[1];if(!path){try{const parsed=new URL(withoutVariant);if(NGA_HOST_RE.test(parsed.hostname)){const match=parsed.pathname.match(/^\/(?:attachments\/)?(mon_\d+\/.+)$/i);if(match)path=match[1];}}catch{}}const isDeletionRemnant=/_$/i.test(path);const normalizedPath=path.replace(/\.jp_$/i,'.jpg');const isNga=Boolean(path);return{rawUrl,identity:isNga?'nga:'+normalizedPath.toLowerCase():'url:'+withoutVariant,fullSizeUrl:isNga?'./'+normalizedPath:withoutVariant,path:normalizedPath,variant:variantMatch?(variantMatch[1]||variantMatch[2]||''):'',isNga,isImage:IMAGE_EXT_RE.test(isNga?'./'+normalizedPath:withoutVariant)||isDeletionRemnant,isDeletionRemnant};}
function variantUrls(reference,thumbBits){const result={full:reference.fullSizeUrl};if(!reference.isNga)return result;const bits=Number(thumbBits)||0;if(bits&64)result.medium=reference.fullSizeUrl+'.,medium.jpg';if(bits&32)result.thumb=reference.fullSizeUrl+'.,thumb.jpg';if(bits&16)result.thumbSmall=reference.fullSizeUrl+'.,thumb_s.jpg';if(bits&8)result.thumbTiny=reference.fullSizeUrl+'.,thumb_ss.jpg';return result;}
function attachmentId(raw){return String(raw&&(raw.aid||raw.id||raw.name||'')||'');}
function parseAttachment(raw){if(!raw||typeof raw!=='object')return null;const sourceUrl=normalizeText(raw.attachurl||raw.url||raw.url_full||raw.path);const reference=parseImageReference(sourceUrl);const declaredType=String(raw.type||'').toLowerCase();if(!reference.fullSizeUrl||(declaredType&&declaredType!=='img'&&!reference.isImage)||(!declaredType&&!reference.isImage))return null;return{id:attachmentId(raw),identity:reference.identity,url:reference.fullSizeUrl,sourceUrl,variants:variantUrls(reference,Number(raw.thumb)||0),thumbBits:Number(raw.thumb)||0,type:'img',originalName:String(raw.url_utf8_org_name||raw.filename||raw.name||''),raw,isDeletionRemnant:reference.isDeletionRemnant};}
function buildAttachmentCatalog(attachs){const byIdentity=new Map();for(const raw of Array.isArray(attachs)?attachs:[]){const item=parseAttachment(raw);if(!item||item.isDeletionRemnant)continue;const previous=byIdentity.get(item.identity);byIdentity.set(item.identity,previous?{...previous,...item,variants:{...previous.variants,...item.variants}}:item);}return[...byIdentity.values()];}
function extractLastName(tags){let value='';let match;NAME_TAG_RE.lastIndex=0;while((match=NAME_TAG_RE.exec(String(tags||'')))){if(match[1].trim())value=match[1].trim();}return value;}
function scanPostImages(content){const text=String(content||'');const result=[];let match;IMAGE_TAG_RE.lastIndex=0;while((match=IMAGE_TAG_RE.exec(text))){const ref=parseImageReference(match[2]);if(ref.fullSizeUrl)result.push({url:normalizeText(match[2]),fullSizeUrl:ref.fullSizeUrl,identity:ref.identity,name:extractLastName(match[1]),isDeletionRemnant:ref.isDeletionRemnant,start:match.index,end:IMAGE_TAG_RE.lastIndex,tag:match[0]});}return result;}
function isStandaloneImage(text,image){const start=text.lastIndexOf('\n',image.start-1)+1;const next=text.indexOf('\n',image.end);const end=next<0?text.length:next;return!text.slice(start,image.start).trim()&&!text.slice(image.end,end).trim();}
function scanManagedImages(content){const text=String(content||'');return scanPostImages(text).filter(image=>isStandaloneImage(text,image));}
function normalizeManagedImages(content){const text=String(content||'');const groups=new Map();for(const image of scanManagedImages(text)){if(!groups.has(image.identity))groups.set(image.identity,[]);groups.get(image.identity).push(image);}const replacements=[];for(const group of groups.values()){const named=[...group].reverse().find(image=>image.name);const marker=/^\[\$deleted\]/i.test(group[0].tag)?'[$deleted]':'';const value=marker+(named?'[$name = '+named.name+']':'')+'[img]'+group[0].fullSizeUrl+'[/img]';replacements.push({start:group[0].start,end:group[0].end,value});for(let i=1;i<group.length;i++)replacements.push({start:group[i].start,end:group[i].end,value:''});}replacements.sort((a,b)=>b.start-a.start);let output=text;for(const replacement of replacements)output=output.slice(0,replacement.start)+replacement.value+output.slice(replacement.end);return{content:output,changed:output!==text,removedDuplicates:Math.max(0,replacements.length-groups.size)};}
function mergeAttachmentImages(content,attachs){const catalog=Array.isArray(attachs)&&attachs.every(item=>item&&item.identity&&item.variants)?attachs:buildAttachmentCatalog(attachs);const normalized=normalizeManagedImages(content);const seen=new Set(scanManagedImages(normalized.content).map(image=>image.identity));const missing=catalog.filter(item=>!item.isDeletionRemnant&&!seen.has(item.identity));const suffix=missing.map(item=>'[img]'+item.url+'[/img]').join('\n');return{images:scanManagedImages(normalized.content),missing,catalog,removedDuplicates:normalized.removedDuplicates,content:missing.length?normalized.content+(normalized.content.endsWith('\n')?'':'\n')+suffix:normalized.content};}
function replaceManagedImage(content,targetUrl,replacer){const target=parseImageReference(targetUrl).identity;const text=String(content||'');let changed=false;const next=text.replace(IMAGE_TAG_RE,(whole,names,imageUrl,offset)=>{if(!isStandaloneImage(text,{start:offset,end:offset+whole.length})||parseImageReference(imageUrl).identity!==target)return whole;changed=true;return replacer({reference:parseImageReference(imageUrl),name:extractLastName(names)});});return{content:normalizeManagedImages(next).content,changed};}
function removeImage(content,url){return replaceManagedImage(content,url,()=> '');}
function nameImage(content,url,name){const label=String(name||'').trim();return replaceManagedImage(content,url,({reference})=>(label?'[$name = '+label+']':'')+'[img]'+reference.fullSizeUrl+'[/img]');}
function buildMediaView(images,attachments){return{images:(Array.isArray(images)?images:[]).filter(item=>item&&!item.isDeletionRemnant),attachments:(Array.isArray(attachments)?attachments:[]).filter(item=>item&&!item.isDeletionRemnant)};}
function attachmentState(attachs,attachments,attachmentsCheck){return{items:buildAttachmentCatalog(attachs),attachments:String(attachments||''),attachmentsCheck:String(attachmentsCheck||'')};}
module.exports={attachmentId,attachmentState,buildAttachmentCatalog,buildMediaView,mergeAttachmentImages,nameImage,removeImage,normalizeManagedImages,parseAttachment,parseImageReference,scanManagedImages,scanPostImages,variantUrls};
