import {EditorState, StateEffect, StateField, Compartment} from '@codemirror/state';
import {EditorView, keymap, lineNumbers, highlightActiveLineGutter, drawSelection, Decoration} from '@codemirror/view';
import {defaultKeymap, history, historyKeymap} from '@codemirror/commands';
import {searchKeymap, highlightSelectionMatches} from '@codemirror/search';
import {tokenizeBbcode, resolveHighlightRanges} from './tokenizer.js';
import {measurePerf} from './performance.js';
const setSyntax=StateEffect.define(),setExternal=StateEffect.define();
const markField=StateField.define({create:()=>({syntax:Decoration.none,external:Decoration.none}),update(v,t){let syntax=v.syntax.map(t.changes),external=v.external.map(t.changes);for(const e of t.effects){if(e.is(setSyntax))syntax=e.value;if(e.is(setExternal))external=e.value}return {syntax,external}}});
// Decoration.set cannot combine RangeSets through iteration in a compute facet; expose both sets separately.
const syntaxDecorations=EditorView.decorations.compute([markField],s=>s.field(markField).syntax);
const externalDecorations=EditorView.decorations.compute([markField],s=>s.field(markField).external);
const classes={bracket:'bb-bracket',close:'bb-close',tag:'bb-tag',attribute:'bb-attribute',value:'bb-value',url:'bb-url',color:'bb-color',number:'bb-number',entity:'bb-entity',commentMarker:'bb-comment-marker',commentName:'bb-comment-name',commentFeature:'bb-comment-feature'};
export function createEditorAdapter(parent, options = {}) {
  let view, listeners=options.onChange?[options.onChange]:[], selectionListeners=options.onSelectionChange?[options.onSelectionChange]:[], decorationVersion=0, syntaxRaf=0, cachedDoc=null;
  const darkTheme=new Compartment(), media=matchMedia('(prefers-color-scheme: dark)');
  const theme=dark=>EditorView.theme({'&':{height:'100%'},'.cm-scroller':{overflow:'auto'},'.cm-content':{minWidth:'max-content'},'.cm-gutters':{backgroundColor:'var(--color-gutter-bg)',color:'var(--color-muted)'}},{dark});
  const update=EditorView.updateListener.of(u=>{if(u.docChanged){decorateSyntax();listeners.forEach(f=>f(u))}if(u.selectionSet)selectionListeners.forEach(f=>f(api.getSelection(),u))});
  view=new EditorView({parent,state:EditorState.create({extensions:[lineNumbers(),highlightActiveLineGutter(),history(),drawSelection(),highlightSelectionMatches(),markField,syntaxDecorations,externalDecorations,update,keymap.of([...defaultKeymap,...historyKeymap,...searchKeymap,{key:'Mod-Enter',run:()=>{options.onModEnter?.();return true}}]),darkTheme.of(theme(media.matches))]})});
  const onTheme=e=>view?.dispatch({effects:darkTheme.reconfigure(theme(e.matches))});media.addEventListener('change',onTheme);
  function decorateSyntax(){const version=++decorationVersion,doc=view.state.doc;if(doc===cachedDoc)return;cancelAnimationFrame(syntaxRaf);syntaxRaf=requestAnimationFrame(()=>{syntaxRaf=0;if(!view||version!==decorationVersion||view.state.doc!==doc)return;const text=doc.toString();const tokens=measurePerf('syntax.tokenize',()=>tokenizeBbcode(text),{length:text.length});const ranges=measurePerf('syntax.resolve',()=>resolveHighlightRanges(text.length,tokens),{tokens:tokens.length});const marks=measurePerf('syntax.decorations',()=>ranges.map(r=>Decoration.mark({class:classes[r.type]||''}).range(r.start,r.end)),{ranges:ranges.length});if(!view||version!==decorationVersion||view.state.doc!==doc)return;cachedDoc=doc;view.dispatch({effects:setSyntax.of(Decoration.set(marks,true))})})}
  const api={getText:()=>view.state.doc.toString(),setText(text){view.dispatch({changes:{from:0,to:view.state.doc.length,insert:String(text??'')}})},dispatchChanges(changes,selection){view.dispatch({changes:changes.map(c=>({from:c.start,to:c.end,insert:c.value})),selection,scrollIntoView:!!selection})},getSelection:()=>({from:view.state.selection.main.from,to:view.state.selection.main.to}),setSelection(from,to=from,center=true){view.dispatch({selection:{anchor:from,head:to},scrollIntoView:center});view.focus()},focus:()=>view.focus(),onChange(fn){listeners.push(fn);return()=>listeners=listeners.filter(x=>x!==fn)},onSelectionChange(fn){selectionListeners.push(fn);return()=>selectionListeners=selectionListeners.filter(x=>x!==fn)},setDecorations(extra=[]){const n=view.state.doc.length,marks=extra.filter(r=>r.start>=0&&r.end<=n&&r.start<r.end).map(r=>Decoration.mark({class:r.class||'cm-diagnostic'}).range(r.start,r.end));view.dispatch({effects:setExternal.of(Decoration.set(marks))})},dispose(){media.removeEventListener('change',onTheme);decorationVersion++;cancelAnimationFrame(syntaxRaf);view.destroy();view=null}};decorateSyntax();return api;
}
