const BB_TAGS = new Set(('b i u s del collapse quote code url img flash audio video color size font align list li table tr td th style fixsize span div h hr br crypt random dice pid tid uid mention attach album emoticon left center right justify comment').split(/\s+/));
const STYLE_ATTRIBUTES = new Set(('color background font align width height line-height border-radius left right top bottom rotate filter-drop-shadow dybg display position margin padding opacity transform z-index').split(/\s+/));
const add=(a,start,end,type)=>{if(start<end)a.push({start,end,type})};
function values(text,start,end,out){const v=text.slice(start,end); for(const [type,re] of [['url',/(?:https?:\/\/|\.\/|\/attachments\/)[^\s;\]]+/gi],['color',/#[0-9a-f]{3}(?:[0-9a-f]{3})?(?:[0-9a-f]{2})?\b/gi],['number',/(?<![\w.])-?(?:\d+(?:\.\d+)?|\.\d+)(?:rem|px|em|vh|vw|deg|ms|s|%)?(?![\w.]|%[\w])/gi],['entity',/&(?:#\d+|#x[0-9a-f]+|[a-z][a-z0-9]+);/gi]]){let m;while((m=re.exec(v)))add(out,start+m.index,start+m.index+m[0].length,type)}}
function comment(text,start,end,out){const bodyStart=start+1,bodyEnd=end-1,body=text.slice(bodyStart,bodyEnd),m=/^\s*comment\s+(\/\/)\s*/i.exec(body);if(!m)return false;add(out,start,start+1,'bracket');add(out,end-1,end,'bracket');const tagAt=bodyStart+body.search(/comment/i);add(out,tagAt,tagAt+7,'tag');const markerAt=bodyStart+m[0].lastIndexOf('//');add(out,markerAt,markerAt+2,'commentMarker');let a=bodyStart+m[0].length,b=bodyEnd;while(a<b&&/\s/.test(text[a]))a++;while(b>a&&/\s/.test(text[b-1]))b--;if(text[a]!=='$'){add(out,a,b,'comment');return true}add(out,a,a+1,'commentMarker');a++;while(a<b&&/\s/.test(text[a]))a++;const image=/^#([^!\]=]+)!\u56fe\u7247\s*=\s*(.*)$/.exec(text.slice(a,b));if(image){add(out,a,a+1,'commentMarker');add(out,a+1,a+1+image[1].length,'commentName');const feature=a+1+image[1].length;add(out,feature,feature+3,'commentFeature');const eq=text.indexOf('=',feature+3);if(eq>=0&&eq<b){add(out,eq,eq+1,'commentMarker');let u=eq+1;while(u<b&&/\s/.test(text[u]))u++;add(out,u,b,'url')}return true}if(text.slice(a,a+2)==='++'||text.slice(a,a+2)==='--'){add(out,a,a+2,'commentMarker');a+=2}else if(text.slice(b-2,b)==='++'||text.slice(b-2,b)==='--'){add(out,b-2,b,'commentMarker');b-=2}const fm=/!(\u6587\u672c|\u5c5e\u6027)\s*$/.exec(text.slice(a,b));if(fm){const f=a+fm.index;add(out,f,b,'commentFeature');b=f}while(a<b&&/\s/.test(text[a]))a++;while(b>a&&/\s/.test(text[b-1]))b--;add(out,a,b,'commentName');return true}
function tag(text,start,end,out){let c=start+1, stop=end-1;add(out,start,start+1,'bracket');add(out,end-1,end,'bracket');while(c<stop&&/\s/.test(text[c]))c++;if(text[c]==='/'){add(out,c,c+1,'close');c++}const m=/^[\w-]+/.exec(text.slice(c,stop));if(!m||!BB_TAGS.has(m[0].toLowerCase()))return false;const name=m[0].toLowerCase();add(out,c,c+m[0].length,'tag');c+=m[0].length;if(text[c]==='='){add(out,c+1,stop,'value');values(text,c+1,stop,out)}else if(name==='style'||name==='fixsize'){const re=/\S+/g;re.lastIndex=c;let x,expect=false;while((x=re.exec(text))&&x.index<stop){const e=Math.min(x.index+x[0].length,stop),lower=text.slice(x.index,e).toLowerCase(),attr=STYLE_ATTRIBUTES.has(lower);add(out,x.index,e,attr&&!expect?'attribute':'value');if(!attr||expect)values(text,x.index,e,out);expect=attr&&!expect}}else if(c<stop){add(out,c,stop,'value');values(text,c,stop,out)}return true}
export function tokenizeBbcode(text){const out=[],blocked=[];let depth=0,content=-1,m;const re=/\[[^\]\r\n]*\]/g;while((m=re.exec(text))){const n=/^\[\s*(\/?)\s*([\w-]+)/.exec(m[0]),name=n?n[2].toLowerCase():'',closing=!!(n&&n[1]);if(depth&&!(closing&&name==='code'))continue;if(depth&&closing&&name==='code')blocked.push({start:content,end:m.index});const local=[];if(!(name==='comment'?comment(text,m.index,m.index+m[0].length,local):tag(text,m.index,m.index+m[0].length,local)))continue;out.push(...local);if(name==='code'){depth+=closing?-1:1;if(!closing&&depth===1)content=m.index+m[0].length;if(closing&&depth===0)content=-1}}if(depth&&content>=0)blocked.push({start:content,end:text.length});const general=[];values(text,0,text.length,general);out.push(...general.filter(x=>!blocked.some(b=>x.start<b.end&&x.end>b.start)));return out}
export const HIGHLIGHT_PRIORITY={bracket:1,close:2,tag:2,attribute:3,value:1,comment:6,url:5,color:5,number:4,entity:5,commentMarker:6,commentName:5,commentFeature:6};
export function resolveHighlightRanges(length,ranges){
 const normalized=(ranges||[]).map((r,index)=>({...r,start:Math.max(0,r.start),end:Math.min(length,r.end),_index:index,_priority:HIGHLIGHT_PRIORITY[r.type]||0})).filter(r=>r.start<r.end);
 const events=[];for(const r of normalized){events.push({at:r.start,open:true,r},{at:r.end,open:false,r})}events.sort((a,b)=>a.at-b.at||(a.open===b.open?0:a.open?1:-1));
 const active=new Set(),heap=[],out=[];let previous=events.length?events[0].at:0,i=0;
 const better=(a,b)=>a._priority!==b._priority?a._priority>b._priority:a.start!==b.start?a.start<b.start:a._index<b._index;
 const push=r=>{let n=heap.length;heap.push(r);while(n){const parent=(n-1)>>1;if(better(heap[parent],r))break;heap[n]=heap[parent];n=parent;heap[n]=r}};
 const pop=()=>{const top=heap[0],last=heap.pop();if(heap.length){let n=0;heap[0]=last;for(;;){let child=n*2+1;if(child>=heap.length)break;if(child+1<heap.length&&better(heap[child+1],heap[child]))child++;if(better(heap[n],heap[child]))break;[heap[n],heap[child]]=[heap[child],heap[n]];n=child}}return top};
 const winner=()=>{while(heap.length&&!active.has(heap[0]))pop();return heap[0]};
 while(i<events.length){const at=events[i].at,winnerRange=winner();if(at>previous&&winnerRange){const last=out[out.length-1];if(last&&last.type===winnerRange.type&&last.end===previous&&last._source===winnerRange._index)last.end=at;else out.push({...winnerRange,start:previous,end:at,_source:winnerRange._index})}while(i<events.length&&events[i].at===at){const e=events[i++];if(e.open){active.add(e.r);push(e.r)}else active.delete(e.r)}previous=at}
 return out.map(({_index,_priority,_source,...r})=>r);
}
